# Generated by Django 4.1.7 on 2023-03-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habla', '0003_alter_post_status_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'published'), ('draft', 'Draft')], default='draft', max_length=10),
        ),
    ]
