# Generated by Django 4.1.7 on 2023-03-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habla', '0005_alter_message_content_alter_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(),
        ),
    ]
